language: rust
rust:
  - stable
  - beta
  - nightly
notifications:
    webhooks:
        - http://heimdallr.thesharp.org/travis
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo run -p buildinfo-example
